### PR TITLE
Handle input file mutliple

### PR DESCRIPTION
**Pull request by mathieutu**
fix https://github.com/spatie/form-backend-validation/issues/44

I've added some hasOwnProperty conditions because the loops caused some side effects and bug with FileList.

see : https://stackoverflow.com/questions/12735778/for-in-and-hasownproperty

See you! ✋ 
Matt'

### CODE REVIEW

**Comment by ekrist1** [comment]
I tried the new code fix, but it seems like a item & length key is added to the array when posting. I might be wrong, but is guess the normal behaviour would be to only submit the files.

Example from the post request:
Content-Disposition: form-data; name="vacancyImageFiles[item]"
function item() {
    [native code]
}
Content-Disposition: form-data; name="vacancyImageFiles[length]"
2

**Comment by mathieutu** [comment]
@ekrist1 Normally that should not be possible, and this is tested in the PR.
I've seen you deleted your comment, is it ok for you?

>I tried the new code fix, but it seems like a item & length key is added to the array when posting. I might be wrong, but is guess the normal behaviour would be to only submit the files.
>
>Example from the post request:
>Content-Disposition: form-data; name="vacancyImageFiles[item]"
>function item() {
>[native code]
>}
>Content-Disposition: form-data; name="vacancyImageFiles[length]"
>2

**Comment by ekrist1** [comment]
@mathieutu yea, works great :) I forgot an underscore when pasting the code, so the bug was caused by me. I have tested the fix and everything works fine. Thanks for solving the issue and making this great package.

**Comment by sebastiandedeyne** [comment]
Thanks!

**Pull request merged**
