### PR TITLE
Add a method to populate the form

### PR DESCRIPTION
**Pull request by lamberttraccard**
I'm using the same form to create and update.
With the populate method it's easy to setup a form with initials values and populate it afterwards.
Calling form.reset() will still restore the fields to their initial values.

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
Thanks for your contribution, but isn't this the same as `withData`?

https://github.com/spatie/form-backend-validation/blob/043736c8d2a2e6a09dbee21195ad62bba7b58204/src/Form.js#L20

**Comment by lamberttraccard** [comment]
Nope, withData() sets the initial values as well. Calling reset() will reset the form to the data passed to withData, populate() won't.

**Comment by lamberttraccard** [comment]
populate() is used to populate a form after it has been instantiated with initials values. I will give u a use case if needed.

**Comment by lamberttraccard** [comment]
```javascript

  /* globals route */
  import Form from '../../class/Form';

  export default {
    props: {
      dataCustomer: {
        type: Object,
        default: null,
      },
    },

    data() {
      return {
        method: 'post',
        customer: this.dataCustomer,
        form: new Form({
          first_name: '',
          last_name: '',
          company_name: '',
          mobile_phone: '',
          home_phone: '',
          address: '',
          postcode: '',
          city: '',
          email: '',
        }, { resetOnSuccess: !this.dataCustomer }),
      };
    },
    created() {
      if (this.customer) {
        this.method = 'patch';
        this.form.populate(this.customer);
      }
    },
    methods: {
      submit() {
        return this.customer ? this.update() : this.create();
      },
      create() {
        this.form[this.method](route('customers.store'))
          .then( // do something)
          .catch( // do something);
      },
      update() {
        this.form[this.method](route('customers.update', this.customer.id))
          .then( // do something)
          .catch( // do something);
      },
    },

  };
```

**Comment by lamberttraccard** [comment]
Hi @sebastiandedeyne, did you reconsider my PR ?

I could live without 😄, I have extended your class for now, but I think it could be useful for other users.

**Comment by sebastiandedeyne** [comment]
Probably gonna merge this in, just need to find the time to review it :)

**Comment by lamberttraccard** [comment]
Yes of course, take your time :)

**Pull request merged**
